services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trial_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - maps-network
    ports:
      - "9000:9000" # Esta linha mapeia a porta do PHP-FPM

  webserver:
    image: nginx:alpine
    container_name: trial_webserver
    restart: unless-stopped
    ports:
      - "0419:80" 
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - maps-network

  db:
    image: mysql:5.7
    container_name: trial_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trial_db
      MYSQL_USER: trial-user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3321:3306"
    networks:
      - maps-network

networks:
  maps-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
